general.import = [
  "~/.config/alacritty/alacritty-theme/themes/alabaster_dark.yaml"
]

general.live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 1
dynamic_padding = false

  [window.padding]
  x = 5

[font]
size = 12.5

  [font.normal]
  family = "JetBrainsMono Nerd Font"

[scrolling]
history = 100_000
